//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyPushNotificationEntities : DbContext
    {
        public MyPushNotificationEntities()
            : base("name=MyPushNotificationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<G_Branch> G_Branch { get; set; }
        public virtual DbSet<SessionStorage> SessionStorages { get; set; }
        public virtual DbSet<Table_Hagz> Table_Hagz { get; set; }
        public virtual DbSet<Table_LastNum> Table_LastNum { get; set; }
        public virtual DbSet<Table_Server> Table_Server { get; set; }
        public virtual DbSet<Table_Tim_work> Table_Tim_work { get; set; }
    }
}
