//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionStorage
    {
        public int ID { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public string ID_Device { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string TR_Type { get; set; }
        public Nullable<int> page { get; set; }
        public Nullable<int> TurnNumber { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> Id_Cust { get; set; }
    }
}
