//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_LastNum
    {
        public int ID { get; set; }
        public Nullable<int> BranchCode { get; set; }
        public Nullable<int> LastNum { get; set; }
        public string Type { get; set; }
    }
}
